/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x154cc2 = _0x139f;
(function (_0x3cd2ec, _0x34a554) {
    const _0x577f8f = _0x139f, _0x234078 = _0x3cd2ec();
    while (!![]) {
        try {
            const _0x47ead5 = -parseInt(_0x577f8f(0xda)) / 0x1 * (-parseInt(_0x577f8f(0xdb)) / 0x2) + -parseInt(_0x577f8f(0xce)) / 0x3 * (-parseInt(_0x577f8f(0xcb)) / 0x4) + parseInt(_0x577f8f(0xc8)) / 0x5 * (parseInt(_0x577f8f(0xde)) / 0x6) + -parseInt(_0x577f8f(0xdf)) / 0x7 * (parseInt(_0x577f8f(0xdc)) / 0x8) + parseInt(_0x577f8f(0xcf)) / 0x9 * (parseInt(_0x577f8f(0xca)) / 0xa) + -parseInt(_0x577f8f(0xd0)) / 0xb * (-parseInt(_0x577f8f(0xd2)) / 0xc) + -parseInt(_0x577f8f(0xd3)) / 0xd;
            if (_0x47ead5 === _0x34a554)
                break;
            else
                _0x234078['push'](_0x234078['shift']());
        } catch (_0xacd4e1) {
            _0x234078['push'](_0x234078['shift']());
        }
    }
}(_0x45a9, 0x19b10));
const gossip = {}, messageStore = {
        'messages': [],
        'push': function (_0xa4168d) {
            const _0x37c6ee = _0x139f, _0xe21352 = {
                    'UnwaT': function (_0x12f4ae, _0xe093f8) {
                        return _0x12f4ae > _0xe093f8;
                    }
                };
            N = 0xa, messageStore[_0x37c6ee(0xc4)][_0x37c6ee(0xc5)](_0xa4168d), _0xe21352[_0x37c6ee(0xc3)](messageStore[_0x37c6ee(0xc4)]['length'], N) && messageStore[_0x37c6ee(0xc4)]['shift']();
        },
        'has': function (_0x36c4d1) {
            const _0x54da43 = _0x139f;
            return messageStore[_0x54da43(0xc4)]['includes'](_0x36c4d1);
        }
    };
function _0x139f(_0x51f542, _0x136e12) {
    const _0x45a91b = _0x45a9();
    return _0x139f = function (_0x139fe8, _0x29ae8c) {
        _0x139fe8 = _0x139fe8 - 0xc2;
        let _0x147bfa = _0x45a91b[_0x139fe8];
        return _0x147bfa;
    }, _0x139f(_0x51f542, _0x136e12);
}
gossip[_0x154cc2(0xcc)] = function (_0x372929, _0x5bfb7b) {
    const _0x3305aa = _0x154cc2, _0x465ba5 = {
            'bugyb': function (_0x22be35, _0x45128e, _0x463e3c) {
                return _0x22be35(_0x45128e, _0x463e3c);
            },
            'Lrtjo': _0x3305aa(0xcd)
        };
    let _0x44b61f = _0x372929[_0x3305aa(0xd9)], _0x3dac76 = _0x372929['remote'], _0xbf569a = _0x372929[_0x3305aa(0xd4)], _0x7b6170 = _0x372929[_0x3305aa(0xd6)];
    if (messageStore[_0x3305aa(0xdd)](_0xbf569a)) {
        _0x5bfb7b && _0x465ba5[_0x3305aa(0xc9)](_0x5bfb7b, null, new Error(_0x465ba5[_0x3305aa(0xd1)]));
        return;
    }
    global[_0x3305aa(0xd7)][_0x7b6170][_0x3305aa(0xc2)][_0x3305aa(0xc7)](_0x44b61f, _0x3dac76), messageStore['push'](_0xbf569a), _0x3dac76['node'] = {
        'ip': global['nodeConfig']['ip'],
        'port': global['nodeConfig']['port']
    }, global['distribution'][_0x3305aa(0xd5)][_0x3305aa(0xd8)][_0x3305aa(0xc7)](_0x44b61f, _0x3dac76, (_0x4961d2, _0x3bbf9f) => {
        _0x5bfb7b && _0x5bfb7b(_0x4961d2, _0x3bbf9f);
    });
}, module[_0x154cc2(0xc6)] = gossip;
function _0x45a9() {
    const _0x435441 = [
        'mid',
        'local',
        'gid',
        'distribution',
        'comm',
        'message',
        '6knZTWh',
        '28218LwGnyN',
        '8DeKMWG',
        'has',
        '198PjFwbw',
        '404467clYQoL',
        'gossip',
        'UnwaT',
        'messages',
        'push',
        'exports',
        'send',
        '3265IdIzcw',
        'bugyb',
        '861570MovhrF',
        '8akfMyK',
        'recv',
        'Message\x20already\x20received',
        '225kniWlc',
        '9nhEXAE',
        '11CpBuBR',
        'Lrtjo',
        '1556064wuQHLD',
        '2069197wXTfkj'
    ];
    _0x45a9 = function () {
        return _0x435441;
    };
    return _0x45a9();
}/* eslint-enable */
