/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
const _0x54b784 = _0x5750;
function _0x5750(_0x547372, _0x52fa9e) {
    const _0x2647b8 = _0x2647();
    return _0x5750 = function (_0x5750e5, _0x356efc) {
        _0x5750e5 = _0x5750e5 - 0x13c;
        let _0xd68a8a = _0x2647b8[_0x5750e5];
        return _0xd68a8a;
    }, _0x5750(_0x547372, _0x52fa9e);
}
(function (_0x3d74e4, _0x5e55e7) {
    const _0x4645d2 = _0x5750, _0x40d3a0 = _0x3d74e4();
    while (!![]) {
        try {
            const _0x4b4072 = -parseInt(_0x4645d2(0x140)) / 0x1 + -parseInt(_0x4645d2(0x151)) / 0x2 * (parseInt(_0x4645d2(0x163)) / 0x3) + parseInt(_0x4645d2(0x145)) / 0x4 * (parseInt(_0x4645d2(0x149)) / 0x5) + parseInt(_0x4645d2(0x15e)) / 0x6 * (parseInt(_0x4645d2(0x152)) / 0x7) + parseInt(_0x4645d2(0x156)) / 0x8 * (parseInt(_0x4645d2(0x15a)) / 0x9) + -parseInt(_0x4645d2(0x14a)) / 0xa * (parseInt(_0x4645d2(0x142)) / 0xb) + parseInt(_0x4645d2(0x155)) / 0xc;
            if (_0x4b4072 === _0x5e55e7)
                break;
            else
                _0x40d3a0['push'](_0x40d3a0['shift']());
        } catch (_0x4c37e8) {
            _0x40d3a0['push'](_0x40d3a0['shift']());
        }
    }
}(_0x2647, 0xc751a));
function _0x2647() {
    const _0x3bd243 = [
        'random',
        'global',
        'log',
        '928891fRnYnl',
        'IdZXL',
        '10747viEZUa',
        'gossip',
        'getMID',
        '8kHDBKr',
        'distribution',
        'pzicc',
        'subset',
        '619315exXYvv',
        '9530mrRJpP',
        'gid',
        'exports',
        'comm',
        'egGTd',
        'recv',
        'keys',
        '3154BzLaCr',
        '28fRhrXn',
        'RRfPh',
        'MQLhS',
        '22706292vWpQta',
        '2848sPjBDX',
        'idmvB',
        'uUuVI',
        'PahiA',
        '12114hzLhEt',
        'floor',
        'length',
        'TmzYu',
        '1862424mAbTvl',
        'local',
        'cAlBt',
        'groups',
        'port',
        '2253qrvHEd',
        'get',
        'send',
        'Yqwwb',
        'ceil'
    ];
    _0x2647 = function () {
        return _0x3bd243;
    };
    return _0x2647();
}
let gossip = function (_0xcfc8bf) {
    const _0x4c54a2 = _0x5750, _0x58d929 = {
            'Yqwwb': function (_0x206827, _0x407844) {
                return _0x206827 + _0x407844;
            },
            'pzicc': function (_0x51c15d, _0x5f1f5b) {
                return _0x51c15d === _0x5f1f5b;
            },
            'BVmDl': function (_0xdcf033, _0x2780e7) {
                return _0xdcf033 * _0x2780e7;
            },
            'egGTd': function (_0x151e7d, _0x55c035) {
                return _0x151e7d(_0x55c035);
            },
            'IdZXL': _0x4c54a2(0x143),
            'idmvB': _0x4c54a2(0x14f),
            'cAlBt': function (_0x3cd5f4, _0x2dde1d, _0x547e99) {
                return _0x3cd5f4(_0x2dde1d, _0x547e99);
            },
            'CNrFX': function (_0x50ee19, _0x428319, _0x4f3e19) {
                return _0x50ee19(_0x428319, _0x4f3e19);
            },
            'cWynF': _0x4c54a2(0x13e)
        };
    let _0x3554af = {};
    return _0x3554af[_0x4c54a2(0x14b)] = _0xcfc8bf['gid'] || _0x58d929['cWynF'], _0x3554af['subset'] = _0xcfc8bf[_0x4c54a2(0x148)] || function (_0x1a3908) {
        const _0x320bbd = _0x4c54a2;
        return Math[_0x320bbd(0x13c)](_0x58d929[_0x320bbd(0x166)](Math[_0x320bbd(0x13f)](_0x1a3908['length']), 0x1));
    }, {
        'send': (_0x3b1ea9, _0x6e7603, _0xdddc55) => {
            const _0x478053 = _0x4c54a2, _0x1e34c5 = {
                    'XZmXi': function (_0x1d8f90, _0x31ad2a) {
                        const _0x486b79 = _0x5750;
                        return _0x58d929[_0x486b79(0x147)](_0x1d8f90, _0x31ad2a);
                    },
                    'MQLhS': function (_0x3b6596, _0x304936) {
                        return _0x58d929['BVmDl'](_0x3b6596, _0x304936);
                    },
                    'PahiA': function (_0x377f2f, _0x552eeb) {
                        const _0x5d53ba = _0x5750;
                        return _0x58d929[_0x5d53ba(0x14e)](_0x377f2f, _0x552eeb);
                    },
                    'TmzYu': _0x58d929[_0x478053(0x141)],
                    'RRfPh': _0x58d929[_0x478053(0x157)]
                };
            global['distribution']['local'][_0x478053(0x161)][_0x478053(0x164)](_0x3554af[_0x478053(0x14b)], (_0xb8480f, _0x28af2d) => {
                const _0x44db50 = _0x478053, _0x3b0856 = {
                        'uUuVI': function (_0x440bad, _0x2be929) {
                            const _0x2f0ed9 = _0x5750;
                            return _0x1e34c5[_0x2f0ed9(0x154)](_0x440bad, _0x2be929);
                        }
                    };
                let _0x32a33f = _0x3554af[_0x44db50(0x148)](Object[_0x44db50(0x150)](_0x28af2d)), _0x3881a6 = function (_0x12b079) {
                        const _0x40e2db = _0x44db50;
                        let _0x1c22f2 = [];
                        while (_0x1c22f2[_0x40e2db(0x15c)] < _0x32a33f) {
                            let _0x14c846 = Math[_0x40e2db(0x15b)](_0x3b0856[_0x40e2db(0x158)](Math[_0x40e2db(0x13d)](), _0x12b079[_0x40e2db(0x15c)]));
                            _0x1c22f2['push'](_0x12b079[_0x14c846]);
                        }
                        return _0x1c22f2;
                    }, _0x1dd4ff = _0x1e34c5[_0x44db50(0x159)](_0x3881a6, Object[_0x44db50(0x150)](_0x28af2d)), _0x57210f = {}, _0x9147c7 = {}, _0x4db416 = 0x0, _0x1895ce = {
                        'message': _0x3b1ea9,
                        'remote': _0x6e7603,
                        'mid': global[_0x44db50(0x146)]['util']['id'][_0x44db50(0x144)](_0x3b1ea9),
                        'gid': _0x3554af[_0x44db50(0x14b)]
                    };
                for (let _0x34672d of _0x1dd4ff) {
                    let _0xc356e4 = _0x28af2d[_0x34672d], _0x463f75 = {
                            'node': {
                                'ip': _0xc356e4['ip'],
                                'port': _0xc356e4[_0x44db50(0x162)]
                            },
                            'service': _0x1e34c5[_0x44db50(0x15d)],
                            'method': _0x1e34c5[_0x44db50(0x153)]
                        };
                    global[_0x44db50(0x146)][_0x44db50(0x15f)][_0x44db50(0x14d)][_0x44db50(0x165)]([_0x1895ce], _0x463f75, (_0x4d48a3, _0x7ffebd) => {
                        _0x4d48a3 ? _0x9147c7[_0x34672d] = _0x4d48a3 : _0x57210f[_0x34672d] = _0x7ffebd, _0x4db416 += 0x1, _0x1e34c5['XZmXi'](_0x4db416, _0x32a33f) && (_0xdddc55 && _0xdddc55(_0x9147c7, _0x57210f));
                    });
                }
            });
        },
        'at': (_0x58d958, _0x365394, _0xc28846) => {
            const _0x1463c0 = _0x4c54a2;
            let _0x2d1e8c = _0x58d929[_0x1463c0(0x160)](setInterval, _0x365394, _0x58d958);
            _0xc28846 && _0xc28846(null, _0x2d1e8c);
        },
        'del': (_0x5b022d, _0x17aa56) => {
            clearInterval(_0x5b022d), _0x17aa56 && _0x58d929['CNrFX'](_0x17aa56, null, _0x5b022d);
        }
    };
};
module[_0x54b784(0x14c)] = gossip;/* eslint-enable */
