/* eslint-disable */

/*
ATTENTION: This is an obfuscated file. You do not need to understand it.
Do NOT edit this file directly. Use it as a black box.

If you notice any issues with using this file, please contact the TAs.
*/
(function (_0x3c11db, _0x59f9e1) {
    const _0xc153ac = _0x4a02, _0x5a1f55 = _0x3c11db();
    while (!![]) {
        try {
            const _0x208206 = -parseInt(_0xc153ac(0x188)) / 0x1 * (-parseInt(_0xc153ac(0x189)) / 0x2) + -parseInt(_0xc153ac(0x18f)) / 0x3 * (-parseInt(_0xc153ac(0x17f)) / 0x4) + -parseInt(_0xc153ac(0x177)) / 0x5 + -parseInt(_0xc153ac(0x17b)) / 0x6 + -parseInt(_0xc153ac(0x170)) / 0x7 * (parseInt(_0xc153ac(0x173)) / 0x8) + -parseInt(_0xc153ac(0x190)) / 0x9 * (-parseInt(_0xc153ac(0x17a)) / 0xa) + -parseInt(_0xc153ac(0x18e)) / 0xb * (-parseInt(_0xc153ac(0x17e)) / 0xc);
            if (_0x208206 === _0x59f9e1)
                break;
            else
                _0x5a1f55['push'](_0x5a1f55['shift']());
        } catch (_0x5123ff) {
            _0x5a1f55['push'](_0x5a1f55['shift']());
        }
    }
}(_0x1e84, 0x1d6d0));
const status = function (_0x553926) {
    const _0x5aeeaa = _0x4a02, _0x3976ba = {
            'Akfej': function (_0xd4f52f, _0x1dd475) {
                return _0xd4f52f + _0x1dd475;
            },
            'xNqhM': function (_0x573886, _0x54704f, _0x1cf2e2) {
                return _0x573886(_0x54704f, _0x1cf2e2);
            },
            'tFiIV': function (_0x5cf109, _0x56b80b) {
                return _0x5cf109(_0x56b80b);
            },
            'cFcVO': _0x5aeeaa(0x184),
            'lHNLc': 'add',
            'VCjDP': 'status',
            'Wkcnj': _0x5aeeaa(0x182)
        };
    let _0x550c31 = {};
    return _0x550c31[_0x5aeeaa(0x187)] = _0x553926[_0x5aeeaa(0x187)] || _0x3976ba[_0x5aeeaa(0x17c)], {
        'get': (_0x56cd99, _0x5dcb57) => {
            const _0x3333d3 = _0x5aeeaa, _0x295dbe = {
                    'KyGMO': function (_0x5d9701, _0x22a023) {
                        const _0x380794 = _0x4a02;
                        return _0x3976ba[_0x380794(0x18d)](_0x5d9701, _0x22a023);
                    },
                    'YNRjq': function (_0x1ef4e5, _0x2b94c9, _0x23c8ba) {
                        const _0x216cf4 = _0x4a02;
                        return _0x3976ba[_0x216cf4(0x174)](_0x1ef4e5, _0x2b94c9, _0x23c8ba);
                    }
                };
            let _0x2e0188 = [_0x56cd99], _0x167a70 = {
                    'service': _0x3333d3(0x171),
                    'method': _0x3333d3(0x183)
                };
            global[_0x3333d3(0x185)][_0x550c31[_0x3333d3(0x187)]]['comm'][_0x3333d3(0x172)](_0x2e0188, _0x167a70, (_0x13efac, _0x44d279) => {
                const _0x52d332 = _0x3333d3, _0x416d80 = {
                        'bajNt': function (_0x74755f, _0x4591ea) {
                            return _0x295dbe['KyGMO'](_0x74755f, _0x4591ea);
                        }
                    };
                switch (_0x56cd99) {
                case _0x52d332(0x18a):
                    let _0x28e9d4 = Object[_0x52d332(0x18c)](_0x44d279)['reduce']((_0x165c61, _0x10f1fd) => {
                        const _0x5467d1 = _0x52d332;
                        return _0x416d80[_0x5467d1(0x16f)](_0x165c61, _0x10f1fd);
                    }, 0x0);
                    _0x5dcb57(_0x13efac, _0x28e9d4);
                    break;
                default:
                    _0x295dbe[_0x52d332(0x180)](_0x5dcb57, _0x13efac, _0x44d279);
                    break;
                }
            });
        },
        'spawn': (_0x282ca1, _0x370b4e) => {
            const _0x1f7964 = _0x5aeeaa, _0x578b8a = {
                    'UXaWv': function (_0x12f477, _0x2cf0e3, _0x13de0f) {
                        const _0x496ebe = _0x4a02;
                        return _0x3976ba[_0x496ebe(0x174)](_0x12f477, _0x2cf0e3, _0x13de0f);
                    }
                };
            _0x370b4e = _0x370b4e || function () {
            }, global[_0x1f7964(0x185)][_0x1f7964(0x175)]['status'][_0x1f7964(0x181)](_0x282ca1, (_0xa9113, _0x61acbd) => {
                const _0x5b62d7 = _0x1f7964;
                _0xa9113 ? _0x3976ba[_0x5b62d7(0x178)](_0x370b4e, _0xa9113) : global['distribution']['local'][_0x5b62d7(0x184)][_0x5b62d7(0x191)](_0x550c31[_0x5b62d7(0x187)], _0x282ca1, () => {
                    const _0x1d2928 = _0x5b62d7;
                    _0x578b8a[_0x1d2928(0x176)](_0x370b4e, null, _0x61acbd);
                }), distribution[_0x550c31[_0x5b62d7(0x187)]][_0x5b62d7(0x179)][_0x5b62d7(0x172)]([
                    _0x550c31['gid'],
                    _0x282ca1
                ], {
                    'service': _0x3976ba[_0x5b62d7(0x17d)],
                    'method': _0x3976ba[_0x5b62d7(0x186)]
                }, () => {
                });
            });
        },
        'stop': _0x3ee973 => {
            const _0x5a05a7 = _0x5aeeaa;
            distribution[_0x550c31[_0x5a05a7(0x187)]]['comm'][_0x5a05a7(0x172)]([], {
                'service': _0x3976ba[_0x5a05a7(0x18b)],
                'method': 'stop'
            }, _0x3ee973);
        }
    };
};
function _0x4a02(_0xa12a5e, _0x449e27) {
    const _0x1e840a = _0x1e84();
    return _0x4a02 = function (_0x4a0268, _0x19e90d) {
        _0x4a0268 = _0x4a0268 - 0x16f;
        let _0x52017e = _0x1e840a[_0x4a0268];
        return _0x52017e;
    }, _0x4a02(_0xa12a5e, _0x449e27);
}
function _0x1e84() {
    const _0x518221 = [
        'local',
        'UXaWv',
        '896955SamAXj',
        'tFiIV',
        'comm',
        '20LRazCR',
        '1023006VTRbkr',
        'Wkcnj',
        'cFcVO',
        '437040YUNAxG',
        '12xMgsYV',
        'YNRjq',
        'spawn',
        'global',
        'get',
        'groups',
        'distribution',
        'lHNLc',
        'gid',
        '25874pODqgs',
        '14cynWBR',
        'heapTotal',
        'VCjDP',
        'values',
        'Akfej',
        '110ewACCj',
        '93531JZMMea',
        '132417ZGErlF',
        'add',
        'bajNt',
        '1384985TpzAMV',
        'status',
        'send',
        '8EobXOD',
        'xNqhM'
    ];
    _0x1e84 = function () {
        return _0x518221;
    };
    return _0x1e84();
}
module['exports'] = status;/* eslint-enable */
